

# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua


$qsConfig = noctalia-shell
$ipc = qs -c noctalia-shell ipc call

# Env
source=hyprland/env.conf
source=custom/env.conf

# Noctalia
source=noctalia/keybinds.conf
source=noctalia/noctalia-colors.conf

# Default
source=hyprland/execs.conf
source=hyprland/rules.conf
source=hyprland/keybinds.conf
source=hyprland/general.conf
source=hyprland/layers.conf

# Custom
source=custom/general.conf
source=custom/execs.conf