# Main
bind = SUPER, F1, exec, $ipc call plugin:keybind-cheatsheet toggle
bind = SUPER, L, exec, $ipc lockScreen lock
bind = SUPER+Shift, L, exec, $ipc sessionMenu lockAndSuspend
bind = SUPER, V, exec, $ipc launcher clipboard

# Media
bind = SUPER+Shift, N, exec, $ipc media next
bind = SUPER+Shift, B, exec, $ipc media previous
bind = SUPER+Shift, P, exec, $ipc media playPause
bind = SUPER+Shift, O, exec, $ipc media toggle

# Bluetooth
bind = SUPER, U, exec, $ipc bluetooth togglePanel
bind = SUPER, N, exec, $ipc network togglePanel
bind = SUPER, K, exec, $ipc brightness increase
bind = SUPER, J, exec, $ipc brightness decrease
bind = SUPER, H, exec, $ipc bar toggle

# Core binds
bind = SUPER, SPACE, exec, $ipc launcher toggle
bind = SUPER, S, exec, $ipc controlCenter toggle
bind = SUPER, comma, exec, $ipc settings toggle
bind = SUPER, dot, exec, qs -c $ipc show

# Media keys
bind = Ctrl+SUPER, M, exec, $ipc volume muteOutput
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease
