
monitor=, 3440x1440@120, 0x0, 1, vrr, 1, bitdepth, 10, cm, srgb

input {
    kb_layout = gb,tr
    kb_options = grp:caps_toggle,caps:none
}

debug:full_cm_proto = true
cursor:no_hardware_cursors = true
